#service.yaml:
#---
#de
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: hello-world-app
    
    #deployment.yaml:
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstkube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: gcr.io/speedy-aurora-351809/github.com/niketa3008/sample-code-java@sha256:ab487bd6fec0ad15b0140015e00e86fc7e3f1885d9fb64a43d41775c491ad1d1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
