#deployment.yaml:
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstkube
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: gcr.io
        ports:
          - containerPort: 8080
#service.yaml:
#---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: hello-world-app
