#service.yaml:
#---
#de
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: hello-world-app
    
    #deployment.yaml:
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstkube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: gcr.io/speedy-aurora-351809/kube@sha256:c186669efdd0745d28e81f892e02e849a8acfad086f12cf025a53858e1ca340d
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
